### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by codeofsumit** [mikaeljorhult/brackets-autoprefixer#12]
Autoprefixer stopped working today. I re-installed and everything but it just does nothing. Not on save and not with "auto-prefix selected lines".

I'm using
Windows 8.1
brackets 0.40
autoprefixer 0.5.2

Dev Tools in brackets isn't showing any errors.

If you need any information i'd be happy to test & provide it.

**Comment by bengoldman** [comment]
I just wanted to add that I am having the same issue with the Autoprefixer extension not working in my Brackets editor.  I am on a Mac.  I have tried the same fixes codeofsummit reported above.  I am now spot-checking for typos.  Will keep you updated.  Thanks.

**Comment by JeremyLopez** [comment]
Yeah, I still cannot get mine working either.  Does the current version still require a `.json` file telling the add-on how to behave?

**Comment by mariodmpereira** [comment]
Hi all,

I know this is an old post but I've seen a lot of these around, just wanted to share my thoughts.

I got the same issue, autoprefix wasn't working, when in fact it was a mistake in my code that was making in not work.

I had a `margin 0` in a class instead of `margin: 0`, that mistake alone made the extension not work, I had more than 600 lines of CSS but that single line was messing it up.

My advise to anyone with the same problem, recheck your code, copy like 50 lines or so at the same time and keep testing autoprefix until you see it doesn't work, you should hopefully find the problem in your code quickly!

Cheers ;)

**Comment by EzekielCarvalho** [comment]
Hi guys, I'd like to attest the same thing. I had a similar problem with the extension in that it would not auto prefix my code. I found out that it was just a code error that prevented it from functioning properly. Here's my error that I encountered, the same after correcting, led the extension to work very well.  

 border-bottom: :2px solid transparent;

Notice the double colon I've inserted when it should have been single.
